ingress:
  enabled: true
  hosts:
    - docs-worker-pool.docs.staging.corp.mongodb.com

envSecrets:
  MONGO_ATLAS_PASSWORD: my-secrets
  MONGO_ATLAS_USERNAME: my-secrets
  AWS_SECRET_ACCESS_KEY: my-secrets
  AWS_ACCESS_KEY_ID: my-secrets
  SECRET_KEY: my-secrets
  ACCESS_KEY: my-secrets
  GITHUB_BOT_USERNAME: my-secrets
  GITHUB_BOT_PASSWORD: my-secrets

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

probes:
  enabled: true
  path: /liveness
  headers: {}
  liveness:
    httpGet: true
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

persistence:
  enabled: true
  name: docsworker
  size: 10Gi
  mountPath: /home/docsworker
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 3
    memory: 3Gi
