env: 
  jest: true
extends: airbnb-base
plugins: ["jest"]
rules: 
  indent: ["error", 4, {SwitchCase: 1}]
  no-underscore-dangle: off
  no-console: off
  no-prototype-builtins: off
  consistent-return: [warn, {treatUndefinedAsUnspecified: true}]
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: off
  jest/prefer-to-have-length: warn
  jest/valid-expect: error
  new-cap: ["error", { "newIsCapExceptions": ["default"] }]
  func-names: off
